### ISSUE TITLE
Blog guide is missing information

### ISSUE THREAD

**Issue by dhughesbc** [AlchemyCMS/alchemy-guides#120]
This section has a link to a crucual github gist that does not exist: thttps://guides.alchemy-cms.com/best_practice_create_blog_template.html#create-new-page-layout-view

**Comment by dhughesbc** [comment]
Actually several external links the blog tutorial https://guides.alchemy-cms.com/best_practice_create_blog_template.html, all related to Zurb, are broken.  The tutorial would be much more useful to AlchemyCms newbies like me if it did not have external dependencies.

**Comment by tvdeyen** [comment]
Closing, because I will disable issues for this repository. If a guide is missing or wrong, open a PR with proposed changes instead.
