### ISSUE TITLE
Document the new essence validation syntax.

### ISSUE THREAD

**Issue by tvdeyen** [AlchemyCMS/alchemy-guides#38]
The essence validation syntax has changed without documenting it.

We should fix that.

https://github.com/AlchemyCMS/alchemy_cms/issues/714

**Comment by tvdeyen** [comment]
@robinboening could you please update the essence validation guides. 

That would be really great :tada:

**Comment by robinboening** [comment]
This is already documented here: http://guides.alchemy-cms.com/edge/elements.html#element-with-content-validations

Also that best-practice guide to create a form reflects the new syntax: http://guides.alchemy-cms.com/edge/best_practice_create_form.html#creating-a-contact-form-element

I think there is no missing guide where we mention it. I close this issue for now - if you know a missing spot feel free to open it again.

**Comment by tvdeyen** [comment]
Great \o/

Maybe we could also update the [upgrade guide](http://guides.alchemy-cms.com/edge/upgrading.html)?

Although the `rake alchemy:upgrade` task prints the changes, we could mention the new validation syntax at the bottom?
