### ISSUE TITLE
TinyMCE - Add "textcolor" plugin - Toolbar: forecolor & backcolor

### ISSUE THREAD

**Issue by agorneo** [AlchemyCMS/alchemy-guides#73]
**Is your feature request related to a problem? Please describe.**
TinyMCE editor lacks of **buttons for setting the font colour** (foreground and background)

**Describe the solution you'd like**
We can add the `textcolor` plugin which add the buttons: `forecolor` & `backcolor`

**Additional context**
We need to copy the `textcolor` plugin folder to `vendor/assets/javascripts/tinymce/plugins` and add the following to config/initializers/tinymce.rb:
```
Alchemy::Tinymce.plugins += ['textcolor']
Alchemy::Tinymce.init = {
  toolbar: [
    'bold italic underline | strikethrough subscript superscript | numlist bullist indent outdent | removeformat | fullscreen',
    'pastetext | charmap code | undo redo | alchemy_link unlink | help | forecolor backcolor'
  ],
}
```
> PS: In the code above we can use somehow the previous toolbar state. Here I used a default one which maybe it is not always the current one... of course in the Alchemy_CMS code we append them in the currently default toolbar...

**Comment by tvdeyen** [comment]
Closed by #74
