### ISSUE TITLE
New blog guide

### ISSUE THREAD

**Issue by mickenorlen** [AlchemyCMS/alchemy-guides#98]
**Problem**
I've been looking at the blog guide: https://guides.alchemy-cms.com/best_practice_create_blog_template.html.
And I think its a bit strange that the entire blog is on a single page. It doesn't feel generally useful and doesn't give each post its own url.

**Alternatives**
So I've been thinking about how to set up a structure that is more generally useful for most resources.
 - A main `blog_page` with a `post_index` element. 
I think the `post_index` element should be able to select what category of `blog_posts` or if listing all `blog_posts` that are subpages of a certain `blog_page`.
- Separate `blog_post` pages with their own urls. 
I would like to restrict these `blog_posts` to only be creatable under a `blog_page`. Dont think this functionality exists?

**Solution**
I've started developing a new/alternative version of the blog guide. Ofc I'd be happy if you have any concerns, pointers or ideas. I'll get back to you with a first draft.

Here's how it looks with the blog in the page tree :)
![image](https://user-images.githubusercontent.com/9784434/75236374-fc352c00-57bd-11ea-9e3c-326a70e332a0.png)

**Comment by tvdeyen** [comment]
I agree. Looking forward to this

> I would like to restrict these `blog_posts` to only be creatable under a `blog_page`. Dont think this functionality exists?

No, this does not exist but is an interesting idea.

**Comment by mickenorlen** [comment]
Here is a gathering of related feature requests
https://github.com/AlchemyCMS/alchemy_cms/issues/1764

**Comment by tvdeyen** [comment]
Closing, because I will disable issues for this repository. If a guide is missing or wrong, open a PR with proposed changes instead.
